### PR TITLE
TimeZone and Skill update

### PR DESCRIPTION
**Pull request by deepshankaryadav**
Added 1 Skill and 2 Timezones

### CODE REVIEW

**Comment by andMYhacks** [comment]
Hi @deepshankaryadav - you missed a comma after `('CET', 'Centraul Europe (UTC +01:00)')`

Would you be able to fix that and resubmit your pull request?

**Comment by deepshankaryadav** [comment]
Hi @andMYhacks ,

Fixed it.

**Comment by andMYhacks** [comment]
@deepshankaryadav What is your profile #? I'd like to add `Contributor, InfoSec Mentors Project` to your profile :smile:

**Comment by deepshankaryadav** [comment]
Hi @andMYhacks , 
It's 254 👍

**Comment by andMYhacks** [comment]
@deepshankaryadav Updated 👍  Thanks for contributing!

**Pull request merged**
